In [3]:
import numpy as np
import csv

In [5]:
with open('train.csv', 'r') as csvfile:
    reader = csv.reader(csvfile)
    data = []
    for row in reader:
        data.append(row)

In [6]:
#data

In [8]:
# much less coding than in 'clear' Python, 'U75' allows work with numbers and text at the same time
data_1 = np.genfromtxt('train.csv', delimiter=',', dtype='U75')

In [9]:
data_1

array([['Loan_ID', 'Gender', 'Married', ..., 'Credit_History',
        'Property_Area', 'Loan_Status'],
       ['LP001002', 'Male', 'No', ..., '1', 'Urban', 'Y'],
       ['LP001003', 'Male', 'Yes', ..., '1', 'Rural', 'N'],
       ...,
       ['LP002983', 'Male', 'Yes', ..., '1', 'Urban', 'Y'],
       ['LP002984', 'Male', 'Yes', ..., '1', 'Urban', 'Y'],
       ['LP002990', 'Female', 'No', ..., '0', 'Semiurban', 'N']],
      dtype='<U75')

In [10]:
number_of_items = data_1[:5, 2:4]

In [11]:
number_of_items

array([['Married', 'Dependents'],
       ['No', '0'],
       ['Yes', '1'],
       ['Yes', '0'],
       ['Yes', '0']], dtype='<U75')

In [12]:
np.empty(5)
np.full(3,4)

array([4.545e-322, 0.000e+000, 0.000e+000, 3.893e-321, 0.000e+000])

array([4, 4, 4])

In [13]:
np.full((3,4), 'm')

array([['m', 'm', 'm', 'm'],
       ['m', 'm', 'm', 'm'],
       ['m', 'm', 'm', 'm']], dtype='<U1')

In [14]:
np.arange(10)
np.linspace(0,9, 10, dtype=int) # (start, stop, step)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.eye(6,6,-2)
np.identity(6)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [16]:
np.array((2,3))

array([2, 3])

In [17]:
# first option of loading data from text file, it needs the same number of
# values in each row
x, y, z = np.loadtxt('C:\\Users\\14000322\\Desktop\\data.txt',
                  skiprows=2, usecols=(0, 1, 2), dtype='U75', unpack=True)

OSError: C:\Users\14000322\Desktop\data.txt not found.

In [18]:
x
y
z

NameError: name 'x' is not defined

In [ ]:
# Second option - text data from numeric columns are converted by filling_values
# argument, so function genfromtxt takes care of Nan
# genfromtxt is more flexible than loadtxt due to additional arguments
my_array2 = np.genfromtxt('C:\\Users\\14000322\\Desktop\\data.txt', skip_header=1, filling_values=-999)

In [ ]:
my_array2

In [ ]:
# Saving array int text file
x = np.array([[0.0, 5.0, 1.0],[3, 8, 1]])
np.savetxt('text_1.out', x, delimiter='!++!')

In [ ]:
x

In [ ]:
print('The number of dimmensions: ', my_array2.ndim)
print('The number of elements: ', my_array2.size)
print('Memory layout: ', my_array2.flags)
print('Length of one array in bytes: ', my_array2.itemsize)
print('The total consumed bytes by array elements: ', my_array2.nbytes)

In [ ]:
len(my_array2) # possible to get length of array but only on upper level
my_array2.astype(float) # possible to change type of data

In [ ]:
# checking the compability of two arrays
x = np.ones((3,4))
print(x.shape)
y = np.random.random((3,4))
print(y.shape)
x + y  # to add two arrays their dimmensions must be compatible (equal)

In [ ]:
# dimmensions are still comptatible when one of array's dimmension is 1
x = np.ones((3,4))
print(x.shape)
y = np.arange(4)
print(y.shape)
x - y # in every row of x values are subtracted by y appropriate value
(x-y).shape

In [ ]:
np.array(4).size

In [ ]:
np.random.random((5,1,4))

In [ ]:
np.random.random((5,2,4))

In [ ]:
x = np.ones((3,4))
y = np.random.random((5,1,4))
print(x)
print(y)
x + y
(x+y).shape

In [ ]:
x.sum()
y.sum()
(x-y).sum()
(x+y).sum()

In [ ]:
x.min()
y.min()
x.max()
y.max()

In [ ]:
x.cumsum(axis=1)
x.cumsum(axis=0)

In [ ]:
x.mean(); y.mean()

In [ ]:
np.median(x); np.median(y)

In [ ]:
np.median(y, axis=0)

In [ ]:
np.corrcoef?

In [ ]:
np.corrcoef(x)

In [ ]:
np.std(x)
np.std(y)

In [ ]:
x.shape < y.shape
x == y # comparison of all elements of both arrays

In [ ]:
z = np.ones((3,2))
np.array_equal(x, y) # comparison of entire arrays
np.array_equal(x, z)

In [ ]:
np.logical_and(x,y)

In [ ]:
w = np.array([1,2,3,4])
np.logical_and(x,y)

In [ ]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])

In [ ]:
a
b

In [ ]:
a+b # broadcasting is possible when arrays dimmensions are equal or 
# one of them is 1 (dimmensions are compatible), the number of dimmensions
# has not to be the same (x.ndim)

In [ ]:
a = np.array([0, 10, 20, 30])
b = np.array([1, 2, 3])

In [ ]:
a; b

In [ ]:
a[:, np.newaxis] + b

In [ ]:
a[:, np.newaxis] # adding new axis changes the array shape into (4,1)
b

In [ ]:
c = np.array([[1,2,3,4], [5,6,7,8]])

In [ ]:
c

In [ ]:
c[1]

In [ ]:
c[1][2]

In [ ]:
c[1,2]

In [ ]:
c[0:2]

In [ ]:
c[0:2,1]

In [ ]:
bigger_than_4 = (c >=4)

In [ ]:
bigger_than_4

In [ ]:
print(c[c<3])

In [ ]:
c[bigger_than_4]

In [ ]:
my_2d_array = np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
my_2d_array

In [ ]:
my_2d_array[[1,0,1,0],[0,1,2,0]] # returns pairs of elements like(1,0),
# (0,1),(1,2),(0,0)
my_2d_array[[1,0,1,0]][:,[0,1,2,0]] # returns a subset of rows and columns

In [ ]:
#np.lookfor('mean')
#np.info(np.mean) #prints the same info as in return of 'np.mean?'

In [ ]:
print(my_2d_array)
np.transpose(my_2d_array)  # reshapin from (m,k) to (k,m)
                            # making columns replaced with rows 
#my_2d_array.T      #pshorter version of transpose but no arguments

In [ ]:
my_2d_array.shape
np.transpose(my_2d_array).shape

In [ ]:
print(x.shape)
np.resize(x, (6,4))
print(x)

In [ ]:
c = np.ones((3,4))
c.resize((6,4)) # it does not work if orginal array ('c') has been
# referenced earlier
c

In [ ]:
a = np.array([[0,1],[2,3]])
a.resize((2,3))
a

In [ ]:
m = np.array([[2,3,4],[5,6,7]])

In [ ]:
np.resize(m,(3,5))

In [ ]:
x.size
x.reshape((2,6)).size

In [ ]:
m.ravel() #array has been 'flattened' - one dimmension with all elements


In [ ]:
# append array to add new rows or columns
new_array = np.append(my_2d_array, [7,8,9, 10])
new_array

In [ ]:
new_2d_array = np.append(my_2d_array, [[12], [14]], axis=1)
new_2d_array

In [ ]:
np.append(my_2d_array, [[12,14, 19, 20]], axis=0)

In [ ]:
my_2d_array

In [ ]:

my_2d_array.shape
np.array([[7,8,9,10]]).shape
np.append(my_2d_array, [[7,8,9,10]], axis=0)

In [ ]:
# functions like append, insert, delete - work on copies of arrays so 
# do not change their originals
my_2d_array

In [ ]:
# functions insert, delete return 'flattened' array objects
np.delete(my_2d_array, [5]).size
np.insert(my_2d_array, 3, 10).shape

In [ ]:
my_array = np.array([[1,2,3,4], [5,6,7,8]])
my_array
x
print(np.concatenate((my_array,x)))  # the same number of dimmensions(axes)!

In [ ]:
# with 1-dimmension concatenates horizontally
np.concatenate((np.array([1,2,3,4]), np.array([5,6,7,8])))

In [ ]:
b = np.zeros((3,5))
np.concatenate((x, b), axis=1)

In [ ]:
m = np.array([[10,11],[12,13]]).T

np.concatenate((my_array, m), axis=1)

In [ ]:
my_array
my_array[[0,0,1],[0,3,2]]

In [ ]:
my_array[1][3]
my_array[1,2]

In [ ]:
my_array[0:1]
my_array[0:2,2:3]
my_array[:,2]

In [ ]:
np.vstack((my_array, x))

In [ ]:
np.vsplit??

In [ ]:
x = np.arange(16).reshape(4,4)
x

In [ ]:
np.vsplit(x, np.array([2,6]))

In [ ]:
np.vsplit(x, 4)

In [ ]:
y = np.arange(16,32).reshape(4,4)
print(y)

In [ ]:
#np.hstack((x,y))
np.column_stack((x, y)) # hstack and column_stack work similarly

In [ ]:
#np.vstack((x,y))
np.r_[x, y]

In [ ]:
np.r_[0, 3, [5]*2] # can concatenate objects of the same dimmension through rows

In [ ]:
np.hsplit(x, 4)

In [ ]:
my_3d_array = np.array([[[1,2,3,4],[5,6,7,8]], [[1,2,3,4],[9,10,11,12]]], dtype= np.int64)
my_3d_array

In [ ]:
# first array show the counts of array elements belonging to bins
# specified in second array (bin - distance between two numbers),
# default number of bins = 10
np.histogram(my_3d_array)

In [ ]:
# np.histogram only counts element appearances but does not plot it
np.histogram(my_3d_array, bins=range(0, 13))

In [ ]:
import matplotlib.pyplot as plt
plt.hist(my_3d_array.ravel(), bins=range(0,13))
plt.title('Frequency of My 3D Array Elements')
plt.show()

In [ ]:
points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points, points)
z = np.sqrt(xs**2 + ys**2)
plt.imshow(z, cmap=plt.cm.gray)
plt.colorbar()
plt.show()